(() => {
const works=[...document.querySelectorAll('.work')],dialog=document.querySelector('#work-dialog'),photo=document.querySelector('#dialog-image'),title=document.querySelector('#dialog-title'),description=document.querySelector('#dialog-description'),other=document.querySelector('#other-photo');
let index=0,alternate=false,origin;
function show(i){index=(i+works.length)%works.length;const work=works[index];alternate=false;photo.src=work.href;photo.alt=work.querySelector('img').alt;title.textContent=work.dataset.title;description.textContent=work.dataset.description;other.hidden=!work.dataset.extra;other.textContent='Ver outra fotografia';document.querySelector('#counter').textContent=(index+1)+' / '+works.length;}
works.forEach((work,i)=>work.addEventListener('click',event=>{if(event.ctrlKey||event.metaKey||event.shiftKey||event.altKey)return;event.preventDefault();origin=work;show(i);dialog.showModal();document.body.classList.add('modal-open');document.dispatchEvent(new Event('ink-modal'));}));
document.querySelector('#close-dialog').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');document.dispatchEvent(new Event('ink-modal'));origin?.focus({preventScroll:true});});
document.querySelector('#previous').onclick=()=>show(index-1);document.querySelector('#next').onclick=()=>show(index+1);other.onclick=()=>{alternate=!alternate;photo.src=alternate?works[index].dataset.extra:works[index].href;other.textContent=alternate?'Voltar à primeira foto':'Ver outra fotografia';};
dialog.addEventListener('keydown',event=>{if(event.key==='ArrowRight')show(index+1);if(event.key==='ArrowLeft')show(index-1);});
const form=document.querySelector('#project-form'),result=document.querySelector('#form-result');form.addEventListener('submit',event=>{event.preventDefault();const d=new FormData(form),message='Olá, Ioiô! Quero conversar sobre uma tatuagem.\n\nNome: '+(d.get('nome')||'Não informado')+'\nIdeia: '+d.get('ideia')+'\nRegião: '+d.get('regiao')+'\nTamanho: '+(d.get('tamanho')||'A definir');document.querySelector('#message-link').href='https://wa.me/5561993941961?text='+encodeURIComponent(message);result.hidden=false;});form.addEventListener('input',()=>result.hidden=true);
document.querySelector('#load-spotify').onclick=event=>{const frame=document.createElement('iframe');frame.src='https://open.spotify.com/embed/playlist/0EWjd0QwA0xibeRbZ0B7ZD?theme=0';frame.title='Play na tattoo, playlist da Iorrany';frame.allow='encrypted-media; fullscreen; picture-in-picture';document.querySelector('#spotify-player').append(frame);event.currentTarget.hidden=true;};
})();
